# Generated by Django 4.2.7 on 2023-12-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_title_alter_customer_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='english', max_length=20),
        ),
    ]
