# Generated by Django 4.2.7 on 2023-12-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_test_question_checktest_checkquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktest',
            name='level',
            field=models.CharField(default='beginner', max_length=25),
        ),
    ]
