# Generated by Django 4.2.7 on 2023-12-10 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_checktest_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
